# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
	config.vm.box = "ubuntu/trusty64"
	config.vm.synced_folder "/Users/pchadeni", "/home/vagrant"

	config.ssh.forward_env = ["SHELL", "TERM"]
	config.vm.provider "virtualbox" do |vb|
		vb.memory = "4096"
		vb.cpus = "4"
	end

	config.vm.provision :shell, path: "bootstrap.sh"
	config.vm.provision :shell, inline: "ln -s ~/.vimrc /home/vagrant/Cursus/GITPERSO/dotfiles/vimrc"

# Clone Oh My Zsh from the git repo
	config.vm.provision :shell, privileged: false,
	inline: "git clone git://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh"

# Copy in the default .zshrc config file
	config.vm.provision :shell, privileged: false,
	inline: "cp ~/.oh-my-zsh/templates/zshrc.zsh-template ~/.zshrc"

end
