"	SHORTCUTS
""	viw -> select word under cursor
""	yiw -> copy word under cursor
"" :.,2+s/foo/bar/g	-> search foo from the current line -> +2 lines and replace it to bar

syntax on
set cursorline
set showcmd
set statusline="%f%m%r%h%w [%Y] [0x%02.2B]%< %F%=%4v,%4l %3p%% of %L"
set laststatus=2
set smartindent
set ruler
set mouse=a
set backspace=indent,eol,start
set tabstop=4
set shiftwidth=4

set splitright

set colorcolumn=80
set history=100



if has("multi_byte")
  set encoding=utf-8
  setglobal fileencoding=utf-8
else
  echoerr "Sorry, this version of (g)vim was not compiled with +multi_byte"
endif
set number

" Grey background for the popup menu
highlight Pmenu ctermbg=gray guibg=gray

"Use 24-bit (true-color) mode in Vim/Neovim when outside tmux.
"If you're using tmux version 2.2 or later, you can remove the outermost $TMUX check and use tmux's 24-bit color support
"(see < http://sunaku.github.io/tmux-24bit-color.html#usage > for more information.)
if (empty($TMUX))
  if (has("nvim"))
    "For Neovim 0.1.3 and 0.1.4 < https://github.com/neovim/neovim/pull/2198 >
    let $NVIM_TUI_ENABLE_TRUE_COLOR=1
  endif
  "For Neovim > 0.1.5 and Vim > patch 7.4.1799 < https://github.com/vim/vim/commit/61be73bb0f965a895bfb064ea3e55476ac175162 >
  "Based on Vim patch 7.4.1770 (`guicolors` option) < https://github.com/vim/vim/commit/8a633e3427b47286869aa4b96f2bfc1fe65b25cd >
  " < https://github.com/neovim/neovim/wiki/Following-HEAD#20160511 >
  if (has("termguicolors"))
    set termguicolors
  endif
endif
if (has("nvim"))
	set statusline+=%#warningmsg#
	set statusline+=%{SyntasticStatuslineFlag()}
	set statusline+=%*
	let g:syntastic_c_include_dirs = [ '../inc', 'inc', 'libft/inc', 'includes', 'libft/includes']
	let g:syntastic_always_populate_loc_list = 1
	let g:syntastic_auto_loc_list = 1
	let g:syntastic_check_on_open = 1
	let g:syntastic_check_on_wq = 0

	colorscheme onedark
endif
let g:lightline = {
  \ 'colorscheme': 'onedark',
  \ }


let g:syntastic_mode_map = { 'passive_filetypes': ['python'] }
" Go back to the current working folder directory
map \ :Explore<CR>
