ZSH=$HOME/.dotfiles/zsh/.oh-my-zsh
# You can change the theme with another one:
#   https://github.com/robbyrussell/oh-my-zsh/wiki/themes
ZSH_THEME="robbyrussell"
#
# Useful plugins for Rails development with Sublime Text
plugins=(gitfast last-working-dir common-aliases zsh-syntax-highlighting history-substring-search)

# Prevent Homebrew from reporting - https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Analytics.md
export HOMEBREW_NO_ANALYTICS=1

# Actually load Oh-My-Zsh
source "${ZSH}/oh-my-zsh.sh"
unalias rm # No interactive rm by default (brought by plugins/common-aliases)

# Rails and Ruby uses the local `bin` folder to store binstubs.
# So instead of running `bin/rails` like the doc says, just run `rails`
# Same for `./node_modules/.bin` and nodejs
export PATH="./bin:./node_modules/.bin:${PATH}:/usr/local/sbin"

# Store your own aliases in the ~/.dotfiles/zsh/.aliases file and load the here.

[[ -f "$HOME/.dotfiles/zsh/.aliases" ]] && source "$HOME/.dotfiles/zsh/.aliases"

# Encoding stuff for the terminal
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export BUNDLER_EDITOR="'/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl' -a"

# Add personnal binaries into the PATH env variable

if [ -z "${PATH-}" ];
  then export PATH=/usr/local/bin:/usr/bin:/bin;
else
  export PATH=${HOME}/Development/mybin:$PATH;
fi

# Display hexadecimal conversions

function fhex() { echo "ibase=16; $1" | bc }
function thex() { echo "obase=16; $1" | bc }

case `uname` in
	Darwin*)
	  export PATH="${HOME}/.brew/bin:${PATH}"
	;;
esac

export MAIL="${USER}@student.42.fr"

#########################################################
#                   BASIC CONFIG                        #
#########################################################


# Launch Visual Studio Code
code () { VSCODE_CWD="$PWD" open -n -b "com.microsoft.VSCode" --args $* ;}

setopt noincappendhistory
setopt nosharehistory

function set_conda {
    HOME=$(echo ~)
    INSTALL_PATH="$HOME/.dotfiles/.python_conda"
    MINICONDA_PATH=$INSTALL_PATH"/miniconda3/bin"
    PYTHON_PATH=$(which python)
    SCRIPT="Miniconda3-latest-MacOSX-x86_64.sh"
    REQUIREMENTS="jupyter numpy pandas"
    DL_LINK="https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh"
    if echo $PYTHON_PATH | grep -q $INSTALL_PATH; then
        echo "good python version :)"
    else
    cd
    if [ ! -f $SCRIPT ]; then
        curl -LO $DL_LINK
        fi
        if [ ! -d $MINICONDA_PATH ]; then
            sh $SCRIPT -b -p $INSTALL_PATH"/miniconda3"
    fi
    conda install -y $(echo $REQUIREMENTS)
    clear
    echo "Which python:"
    which python
    if grep -q "^export PATH=$MINICONDA_PATH" ~/.zshrc
    then
        echo "export already in .zshrc";
    else
        echo "adding export to .zshrc ...";
        echo "export PATH=$MINICONDA_PATH:\$PATH" >> $HOME/.zshrc
		echo "export PATH=$INSTALL_PATH/miniconda/bin/condabin:\$PATH" >> $HOME/.zshrc
    fi
	source $HOME/.zshrc
fi
}
