ZSH=$HOME/.oh-my-zsh
# You can change the theme with another one:
#   https://github.com/robbyrussell/oh-my-zsh/wiki/themes
ZSH_THEME="robbyrussell"
#
# Useful plugins for Rails development with Sublime Text
plugins=(gitfast last-working-dir common-aliases zsh-syntax-highlighting history-substring-search)

# Prevent Homebrew from reporting - https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Analytics.md
export HOMEBREW_NO_ANALYTICS=1

# Actually load Oh-My-Zsh
source "${ZSH}/oh-my-zsh.sh"
unalias rm # No interactive rm by default (brought by plugins/common-aliases)

# Rails and Ruby uses the local `bin` folder to store binstubs.
# So instead of running `bin/rails` like the doc says, just run `rails`
# Same for `./node_modules/.bin` and nodejs
export PATH="./bin:./node_modules/.bin:${PATH}:/usr/local/sbin"

# Store your own aliases in the ~/.dotfiles/zsh/.aliases file and load the here.

[[ -f "$HOME/.dotfiles/zsh/.aliases" ]] && source "$HOME/.dotfiles/zsh/.aliases"

# Encoding stuff for the terminal
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export BUNDLER_EDITOR="'/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl' -a"

# Add personnal binaries into the PATH env variable

if [ -z "${PATH-}" ];
  then export PATH=/usr/local/bin:/usr/bin:/bin;
else
  export PATH=${HOME}/bin:$PATH;
fi

# Display hexadecimal conversions

function fhex() { echo "ibase=16; $1" | bc }
function thex() { echo "obase=16; $1" | bc }

#########################################################
#                   BASIC CONFIG                        #
#########################################################


# Launch Visual Studio Code
code () { VSCODE_CWD="$PWD" open -n -b "com.microsoft.VSCode" --args $* ;}

setopt noincappendhistory
setopt nosharehistory
#
# Working aliases
export CDPATH=$HOME/Work
# Add date on the prompt's right
export RPROMPT="[%D{%f/%m/%Y | %T}]"

# Set correct binding for arrows
bindkey "^[[1;2C" forward-word
bindkey "^[[1;2D" backward-word
bindkey "^[^[[C" forward-word
bindkey "^[^[[D" backward-word

# Setup variables for pyenv
export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
